Vagrant.configure("2") do |config|
  #执行脚本
  config.vm.provision "shell", path: "bootstrap_linux.sh"

  # Master 节点
  config.vm.define "linux-zzn" do |master|
    master.vm.box = "bento/ubuntu-22.04"
    master.vm.hostname = "linux-zzn"
    master.vm.network "private_network", ip: "192.168.56.130"
    master.vm.provider "virtualbox" do |v|
      v.name = "linux-zzn"
      v.memory = 2048
      v.cpus = 2
    end
  end
end